In [1]:
#IMPORTAMOS LAS VARIABLES 
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay
)

In [11]:
#CARGAMOS EL DATASET

In [12]:
iris = load_iris(as_frame=True)

In [13]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [14]:
# Convertimos los datos en DataFrame
dfIris = iris.frame
dfIris.head(2)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0

In [15]:
dfIris.tail(2)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [16]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [18]:
#Cambiamos la columna de Target por Especie
dfIris.rename(columns={"target" : "species"}, inplace=True)

In [19]:
##variables predictorias

## Variables predictoras y Variable objetivo

X (Variables predictoras) son aquellas que me permiten hacer la prediccion
y (objetivo) Lo que quiero predecir

In [27]:
#Variables predictoras
X = dfIris.drop(columns=["species"])

In [28]:
# Variable objetivo
y = dfIris["species"]

In [29]:
print("---Variables predictoras---")
print(X.columns)
print("---Variable Objetivo ----")
print(y.name)

---Variables predictoras---
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')
---Variable Objetivo ----
species

## División del conjunto de datos

*Training Set:* Datos para entrenamiento.

*Testing Set:* Datos no vistos por el modelo, para prueba.

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X, #Variables predictoras
    y, #Variable objetivo,
    test_size = 0.20,
    random_state=42,
    stratify=y
)

In [32]:
print("X_train: ", X_train.shape)
print("X_test: ", X_test.shape)
print("--------------------------")
print("y_train: ", y_train.shape)
print("y_test: ", y_test.shape)

X_train:  (120, 4)
X_test:  (30, 4)
--------------------------
y_train:  (120,)
y_test:  (30,)

# Escalado de las variables

In [33]:
scaler = StandardScaler()

In [34]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [39]:
print("-----------Datos sin escalar------------")
print(X_train.head(5))
print("-----------Escalados------------")
print(X_train_scaled[:5])

-----------Datos sin escalar------------
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
106                4.9               2.5                4.5               1.7
76                 6.8               2.8                4.8               1.4
9                  4.9               3.1                1.5               0.1
89                 5.5               2.5                4.0               1.3
-----------Escalados------------
[[-1.72156775 -0.33210111 -1.34572231 -1.32327558]
 [-1.12449223 -1.22765467  0.41450518  0.6517626 ]
 [ 1.14439475 -0.5559895   0.58484978  0.25675496]
 [-1.12449223  0.11567567 -1.28894078 -1.45494479]
 [-0.40800161 -1.22765467  0.13059752  0.12508575]]

# Entrenamiento del modelo

In [40]:
# Creamos una instancia del algoritmo
modelo = KNeighborsClassifier(
    n_neighbors = 3 #numero de vecinos a comparar
)

In [41]:
# Entrenamos con los datos de entrenamiento
modelo.fit(
    X_train_scaled,
    y_train
)

KNeighborsClassifier(n_neighbors=3)

# Prediccion con los datos de prueba

In [42]:
prediccion = modelo.predict(X_test_scaled)

In [43]:
pd.DataFrame({
    "Especie real" : y_test.values,
    "Especie predicha" : prediccion
}).head(10)

   Especie real  Especie predicha
0             0                 0
1             2                 2
2             1                 1
3             1                 1
4             0                 0
5             1                 1
6             0                 0
7             0                 0
8             2                 2
9             1                 1

# variables importantes

# Evaluacion del modelo